### ISSUE TITLE
SCAM

### ISSUE THREAD

**Issue by yearny** [MarsFi/POWToken#1]
Be careful! This is NOT the original Marscoin cryptocurrency !!!

**Comment by fluke9** [comment]
It may share the name but it seems to be legitimate.

**Comment by AlejandroDeLaTorre** [comment]
it's called MARS not Marscoin.

**Comment by yearny** [comment]
shut up scammer

Am Mi., 17. Feb. 2021 um 16:04 Uhr schrieb Alejandro De La Torre <
notifications@github.com>:
